language: cpp
compiler: gcc
- secure: "dQjlHA9MsbbypYTrCdn2zXIum/+uGR/f2/HA6p0a559wVD7LRcHRCnpSilvsZj835fAVJGs0e48ZIbYSEcR0UDcNBG9pV9rLcMohl/9P7OoRuf2btk6NhnyoqArzWVfILJ9MzjrYrja5f+sTmoYl8RlMKkq1Q4TbkzafC2AONfSTSzORdJdxsrDE3wKqy2xsnL+dX0YFbe0kAT/AuvKoV/adhXXktZm7PT1v0b1exckm/YkN3nyf0V0dwi1NY7TtglDcuFUWNrHzLDR8dwbamjGk0aTnlabR6/KpH5dVAKE6fvbCYochAyV8dUa/tydc6xj21hJFH12gvrBHVLbvcPJJmuJ/oQ5nLO/oFSqaxLXTvARIbXULeXSVdffPTriusF6pDJCG2hdcSAHO7ekXXFlve3A1WMT4+g8B0pfs47gvSBZ/nvz9pbToWXMwtbNO4uz28v8hfExObZHUt0uPYwTVCXLWmCdUixbbAtadvaUZc4JgkcStMIb/orXo3zq+QWpRLPNmW9W5POAURIWZy4FF/ylKyi2FejBWkYWmKfGMI3Fx6hAEBB0jFj5gBpDS+Td38Lxa6YABJH8FQm3zRO1zHcr6BHCBWdsKzIVWEtY6zMZnytxOi3N1koKkVLJdwOGASsi66YDdv/+9ogen/aj4pmwOkYlJpSahtPFX7gc="

before_install:
 - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
 - sudo apt-get -qq update
 - sudo apt-get install libboost1.54-all-dev -y
 - sudo apt-get install libdb-dev libdb++-dev -y
 - sudo apt-get install libminiupnpc-dev -y

addons:
  coverity_scan:
    project:
      name: "charlesrocket/axe"
      description: "<Your project description here>"
      build_command_prepend: "/src"
    build_command: "- cd src  - mkdir obj  - cd obj  - mkdir zerocoin  - cd ..  - make -f makefile.unix"
    branch_pattern: master

script:
 - cd src
 - mkdir obj
 - cd obj
 - mkdir zerocoin
 - cd ..
 - make -f makefile.unix
