language: cpp
compiler: gcc

script:
 - apt-get update
 - sudo apt-get install libboost1.54-all-dev y
 - sudo apt-get install libdb-dev libdb++-dev y
 - sudo apt-get install libminiupnpc-dev y
 - cd src
 - mkdir obj
 - cd obj
 - mkdir zerocoin
 - cd ..
 - make -f makefile.unix 
