language: cpp
compiler: gcc
- secure: "kHh4AgjCRydcGoWPDl0q6/jSf3HvQaERWj928BVlCABUS5jP8hXSJ3HoLhEcEDQ9FKEwNLehUZKd1+DBc/rGpXH6cBGPMZIvrRekYFuVNpmqoV9/O8L1EjqVOPt9lXYatIV7Ecylz14D+TzSdz+KguNKHN3G0JiTrV7+vGuc8WfwB4Ewk25ENfwNixRlwadrm8jeXUcyFdbpTk2T3NjqG5lAYJqpFbv5T52IuINN4j090LeLOIsECQY9U/zguSIA11+XN+b1WYlFBb34Qpm21+UW18AgczNmCf0guuhACBa8/n1LG2CBWXm+1ZUkuJK5wTGOFlbznLBtvI0ZUz+T8uRPqzrypKVGg054q8GeeLY2Dl2zt7pgF0f8JpTkILWViBApXlGXNZTkBHbhvGMsF2iefnggDiJVX1e+9NcVUWAnCI5yRwTAc8qjgItlIzZgli6NZHvxOpzme5+3Z5DAePPBtDnUFZAC8R/F5p9jE/uqXMGUgy/OVxcoWiH3zdBK8Lmqt0LtBSH0hiubDPuaAid2yoWPU/YAUqh+5uQa59LFGMyS/wQgM0lNul7iYq9rc5VibsnEnlP0xbdZ8NBidN2kTxhngK/Cd8If8zhe3Svw8RGvOkhcMoPlht5Ou+txt9H7FDioOK29NlBXJ0ob6YSZENCCzZEQZz6ltxU0W0U="

before_install:
 - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
 - sudo apt-get -qq update
 - sudo apt-get install libboost1.54-all-dev -y
 - sudo apt-get install libdb-dev libdb++-dev -y
 - sudo apt-get install libminiupnpc-dev -y

addons:
  coverity_scan:
    project:
      name: "charlesrocket/axe"
      description: "<Your project description here>"
    branch_pattern: main

script:
 - cd src
 - mkdir obj
 - cd obj
 - mkdir zerocoin
 - cd ..
 - make -f makefile.unix
