sudo: true
language: cpp
compiler: gcc

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install libboost1.54-all-dev -y
 - sudo apt-get install libdb-dev libdb++-dev -y
 - sudo apt-get install libminiupnpc-dev -y

script:
 - cd src
 - mkdir obj
 - cd obj
 - mkdir zerocoin
 - cd ..
 - make -f makefile.unix
 - cd ..
 - ./get_code_cov.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash)
